// Proposed actions — Demo Brief §6.
// Fill: Dyne. Strategy-to-Action board. Spread across MOs, with a few
// in-flight statuses and Strategy Impact flags so the board reads live.

export const ACTIONS = [
  {
    id: 'A1',
    title: 'Commission 52-week FORCE biodistribution summary (skeletal + cardiac + CNS)',
    fromInsightRef: 'AI1',
    moRef: 'MO1',
    owner: 'Platform Science',
    dueBy: '2026-Q3',
    status: 'Started',
    strategyImpact: 'Confirmed',
  },
  {
    id: 'A2',
    title: 'Develop "FORCE vs Avidity AOC" community-facing one-pager',
    fromInsightRef: 'AI3',
    moRef: 'MO2',
    owner: 'Medical Comms',
    dueBy: '2026-Q2',
    status: 'Started',
    strategyImpact: 'Confirmed',
  },
  {
    id: 'A3',
    title: 'Co-create DMD sequencing algorithm with 3–5 DMD center PIs (FORCE vs gene therapy)',
    fromInsightRef: 'AI1',
    moRef: 'MO2',
    owner: null,
    dueBy: null,
    status: 'Proposed',
    strategyImpact: null,
  },
  {
    id: 'A4',
    title: 'Build ACHIEVE endpoint primer for community neurologists (DM1)',
    fromInsightRef: 'AI2',
    moRef: 'MO4',
    owner: 'Field Medical',
    dueBy: '2026-Q2',
    status: 'Accepted',
    strategyImpact: 'Confirmed',
  },
  {
    id: 'A5',
    title: 'Scope cross-indication KOL engagement model (rather than disease-siloed)',
    fromInsightRef: 'AI4',
    moRef: 'MO3',
    owner: 'Medical Strategy',
    dueBy: '2026-Q3',
    status: 'Started',
    strategyImpact: 'Changed',
  },
  {
    id: 'A6',
    title: 'Expedite Pompe durability comparator vs ERT (messaging pre-IND)',
    fromInsightRef: 'AI5',
    moRef: 'MO2',
    owner: null,
    dueBy: null,
    status: 'Proposed',
    strategyImpact: null,
  },
  {
    id: 'A7',
    title: 'Commission FSHD DUX4 protein-suppression evidence review',
    fromInsightRef: 'AI6',
    moRef: 'MO1',
    owner: null,
    dueBy: null,
    status: 'Proposed',
    strategyImpact: null,
  },
  {
    id: 'A8',
    title: 'Stand up structured insight capture pipeline (Aurivian integration)',
    fromInsightRef: 'AI7',
    moRef: 'MO4',
    owner: 'Eric Krauter',
    dueBy: '2026-Q2',
    status: 'Started',
    strategyImpact: 'Confirmed',
  },
  {
    id: 'A9',
    title: 'Engage Pompe patient advocacy community on ERT-to-oligo transition narrative',
    fromInsightRef: 'AI5',
    moRef: 'MO3',
    owner: null,
    dueBy: null,
    status: 'Declined',
    strategyImpact: 'Challenged',
  },
];
