// Artifact library — outputs completed agent tasks have produced.
// Fill: Dyne Q2 2026.

export const ARTIFACTS = [
  {
    id: 'ART1',
    title: 'Strategy-to-Action — Q2 2026',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-04-14',
    summary: 'Full Q2 Strategy-to-Action: 3 ISP pillars, 4 MOs with coverage scoring, 7 prioritised insights, 9 proposed actions, and 4 Gap Radar suggestions.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Med Info queries', 'MDA 2026 debriefs', 'WMS 2025 debriefs'],
    sizeLabel: '2.1 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART2',
    title: 'MDA 2026 Orlando Debrief — FORCE vs Gene Therapy Discourse',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2026-03-22',
    summary: 'Synthesis of DMD and DM1 scientific conversations at MDA 2026, including Elevidys / microdystrophin positioning and the emerging FORCE narrative. Competitor visibility analysis included.',
    dataSources: ['MDA 2026 abstracts', 'Late-breaker session transcripts', 'Social commentary'],
    sizeLabel: '1.9 MB',
    provenance: 'synthesized-from-public',
  },
  {
    id: 'ART3',
    title: 'Cross-Indication KOL Map — April 2026',
    type: 'interactive',
    agent: 'LUCA',
    taskType: 'KOL Selection & Profiling',
    dateCreated: '2026-04-10',
    summary: 'Live KOL map highlighting the 5 credibly cross-indication voices (Monckton, Tawil, Schoser, Lochmüller, Züchner) plus 2 emerging watchlist entries. Sentiment and platform-view overlays.',
    dataSources: ['PubMed', 'MDA / WMS / ICNMD program data', 'CRM interaction history'],
    sizeLabel: 'In-app',
    provenance: 'synthesized',
  },
  {
    id: 'ART4',
    title: 'FORCE vs Avidity AOC — Community One-Pager (Draft)',
    type: 'pptx',
    agent: 'NOVA',
    taskType: 'Medical Insights Report',
    dateCreated: '2026-04-07',
    summary: 'Community-facing one-pager addressing AI3 (FORCE vs AOC differentiation debate). Non-internal language. Draft for Medical Comms review.',
    dataSources: ['MSL field notes', 'Ad board transcripts', 'Public literature on FORCE and AOC biophysics'],
    sizeLabel: '2.4 MB',
    provenance: 'synthesized',
  },
  {
    id: 'ART5',
    title: 'ACHIEVE Endpoint Primer for Community Neurologists',
    type: 'pdf',
    agent: 'NOVA',
    taskType: 'Evidence Generation',
    dateCreated: '2026-04-02',
    summary: 'Clinician-facing primer on DM1 functional endpoints (myotonia, grip, DM1-ActiveC) and candidate-selection framing for ACHIEVE-eligible patients. Addresses AI2.',
    dataSources: ['Public ACHIEVE protocol', 'PubMed DM1 endpoint literature', 'Ad board'],
    sizeLabel: '3.3 MB',
    provenance: 'synthesized-from-public',
  },
  {
    id: 'ART6',
    title: 'MDA 2025 → MDA 2026 Sentiment Trend',
    type: 'interactive',
    agent: 'ARIA',
    taskType: 'Congress Intelligence',
    dateCreated: '2026-03-25',
    summary: 'Year-over-year sentiment shift across DMD / DM1 / FORCE platform discourse. Competitor visibility trend (Sarepta, Avidity) and social amplification overlay.',
    dataSources: ['MDA 2025 abstracts', 'MDA 2026 abstracts', 'Social commentary'],
    sizeLabel: 'In-app',
    provenance: 'synthesized-from-public',
  },
  {
    id: 'ART7',
    title: 'WMS 2025 Vienna — FORCE Delivery Session Summary',
    type: 'pdf',
    agent: 'ARIA',
    taskType: 'Congress Debrief',
    dateCreated: '2025-10-15',
    summary: 'Post-congress synthesis of the FORCE biodistribution session including Q&A, competitor delivery approaches (Avidity AOC, PepGen EDO), and KOL reaction.',
    dataSources: ['WMS 2025 abstracts', 'Session recordings', 'Attendee commentary'],
    sizeLabel: '1.7 MB',
    provenance: 'synthesized-from-public',
  },
];
