// Congress roster — Demo Brief §3 (+ §8 for per-congress ARIA data).
// Fill: Neuromuscular flagship congresses relevant to Dyne (MDA, WMS,
// ICNMD, ASGCT). Public congress dates; presentations inferred from
// Dyne's corporate IR announcements and congress abstract books.

export const CONGRESS_OPTIONS = [
  {
    id: 'mda-2025',
    name: 'MDA 2025',
    fullName: 'MDA Clinical & Scientific Conference 2025',
    location: 'Dallas, TX',
    date: 'Mar 16–19, 2025',
    available: true,
    provenance: 'public',
  },
  {
    id: 'mda-2026',
    name: 'MDA 2026',
    fullName: 'MDA Clinical & Scientific Conference 2026',
    location: 'Orlando, FL',
    date: 'Mar 15–18, 2026',
    available: true,
    provenance: 'public',
  },
  {
    id: 'trend-mda-25-26',
    name: 'Trend: MDA 2025 → 2026',
    fullName: 'Sentiment trend MDA 2025 → MDA 2026 (DMD / DM1 / FORCE)',
    location: '—',
    date: '—',
    available: true,
    isTrend: true,
  },
  {
    id: 'wms-2025',
    name: 'WMS 2025',
    fullName: 'World Muscle Society Congress 2025',
    location: 'Vienna, Austria',
    date: 'Oct 7–11, 2025',
    available: true,
    provenance: 'public',
  },
  {
    id: 'icnmd-2026',
    name: 'ICNMD 2026',
    fullName: 'International Congress on Neuromuscular Diseases 2026',
    location: 'Paris, France',
    date: 'Jun 15–19, 2026',
    available: false,
    comingSoon: true,
    provenance: 'public',
  },
  {
    id: 'asgct-2026',
    name: 'ASGCT 2026',
    fullName: 'American Society of Gene & Cell Therapy Annual Meeting 2026',
    location: 'New Orleans, LA',
    date: 'May 12–16, 2026',
    available: false,
    comingSoon: true,
    provenance: 'public',
  },
  { id: 'ppmd',    name: 'PPMD',         fullName: 'Parent Project Muscular Dystrophy Annual Connect Conference',     location: '—', date: '—', available: false, comingSoon: true, provenance: 'public' },
  { id: 'mdf',     name: 'MDF Conf.',    fullName: 'Myotonic Dystrophy Foundation Annual Conference',                 location: '—', date: '—', available: false, comingSoon: true, provenance: 'public' },
  { id: 'fshd-soc', name: 'FSHD Society', fullName: 'FSHD Society International Research Congress',                   location: '—', date: '—', available: false, comingSoon: true, provenance: 'public' },
];
