// KOL roster — Demo Brief §7.
// LUCA's core dataset. Neuromuscular KOLs across DMD / DM1 / Pompe / FSHD.
//
// Names, institutions, and broad research focus are sourced from public
// PubMed records, congress programs (MDA, WMS, ICNMD, ASGCT), and
// institutional NM-center pages. Interaction counts, sentiment scores,
// engagement tiers, and recommended strategies are synthesized for the demo.

export const KOL_DATA = [
  // ─── Cross-indication voices — the rare portfolio speakers (MO3 priority) ───
  {
    id: 'kol-1',
    name: 'Darren Monckton',
    institution: 'University of Glasgow',
    city: 'Glasgow',
    country: 'UK',
    region: 'Europe',
    specialty: 'Myotonic Dystrophy & RNA Biology',
    subIndications: ['dm1', 'fshd'],
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-101', 'dyne-fshd'],
    recentInteractions: 7,
    publications: 220,
    focusAreas: ['DM1 CTG repeat biology', 'RNA gain-of-function', 'FSHD DUX4 regulation'],
    conferenceAppearances: 12,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'FORCE-curious; authored translational commentary on TfR1-mediated delivery',
    crossIndication: true,
    recommendedStrategy:
      'Anchor cross-indication scientific-exchange program. One of the rare credible voices spanning DM1 and FSHD.',
    email: 'darren.monckton@glasgow.ac.uk',
    provenance: 'public',
  },
  {
    id: 'kol-2',
    name: 'Rabi Tawil',
    institution: 'University of Rochester Medical Center',
    city: 'Rochester',
    country: 'USA',
    region: 'North America',
    specialty: 'FSHD & DM1',
    subIndications: ['fshd', 'dm1'],
    influenceScore: 94,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-fshd', 'dyne-101'],
    recentInteractions: 4,
    publications: 175,
    focusAreas: ['FSHD clinical trials', 'DUX4 regulation', 'DM1 natural history'],
    conferenceAppearances: 11,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'Strong platform voice; Rochester center runs both DM1 and FSHD programs',
    crossIndication: true,
    recommendedStrategy:
      'Second credible cross-indication KOL (alongside Monckton). Priority for A5 (cross-indication KOL engagement model).',
    email: 'rabi.tawil@urmc.rochester.edu',
    provenance: 'public',
  },
  {
    id: 'kol-3',
    name: 'Stephan Züchner',
    institution: 'University of Miami Miller School',
    city: 'Miami',
    country: 'USA',
    region: 'North America',
    specialty: 'Neuromuscular Genetics',
    subIndications: ['dmd', 'dm1', 'fshd'],
    influenceScore: 86,
    engagementTier: 'Tier 2',
    productAlignment: ['dyne-101', 'dyne-251', 'dyne-fshd'],
    recentInteractions: 2,
    publications: 320,
    focusAreas: ['Neuromuscular genetics', 'Rare disease diagnostics', 'Genotype-phenotype correlation'],
    conferenceAppearances: 7,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'Portfolio-level framing credible; often speaks across indications at MDA',
    crossIndication: true,
    recommendedStrategy:
      'Third cross-indication voice. Engage for platform-level scientific exchange.',
    email: 'szuchner@med.miami.edu',
    provenance: 'public',
  },
  {
    id: 'kol-4',
    name: 'Benedikt Schoser',
    institution: 'LMU University Hospital Munich',
    city: 'Munich',
    country: 'Germany',
    region: 'Europe',
    specialty: 'Pompe & Adult-Onset Neuromuscular Disease',
    subIndications: ['pompe', 'dm1'],
    influenceScore: 89,
    engagementTier: 'Tier 2',
    productAlignment: ['dyne-pompe', 'dyne-101'],
    recentInteractions: 3,
    publications: 195,
    focusAreas: ['Adult-onset Pompe', 'Late-onset DM1', 'Muscle biopsy diagnostics'],
    conferenceAppearances: 8,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'Open to platform framing; authored WMS 2025 piece touching both indications',
    crossIndication: true,
    recommendedStrategy:
      'Cross-indication portfolio voice in EU. Engagement candidate for advocacy-intelligence LP (Gap Radar proposal).',
    email: 'benedikt.schoser@med.uni-muenchen.de',
    provenance: 'public',
  },
  {
    id: 'kol-5',
    name: 'Hanns Lochmüller',
    institution: 'The Ottawa Hospital & University of Ottawa',
    city: 'Ottawa',
    country: 'Canada',
    region: 'North America',
    specialty: 'Rare Neuromuscular Disease',
    subIndications: ['dmd', 'pompe'],
    influenceScore: 87,
    engagementTier: 'Tier 2',
    productAlignment: ['dyne-251', 'dyne-pompe'],
    recentInteractions: 2,
    publications: 280,
    focusAreas: ['Ultra-rare NM disorders', 'Natural history studies', 'EU rare disease networks'],
    conferenceAppearances: 8,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'EU rare-disease network leader; platform-friendly framing',
    crossIndication: true,
    recommendedStrategy:
      'EU engagement node for DMD + Pompe cross-talk. Bridge to ICNMD 2026 scientific committee.',
    email: 'hlochmuller@ohri.ca',
    provenance: 'public',
  },

  // ─── DMD specialists ───
  {
    id: 'kol-6',
    name: 'Jerry Mendell',
    institution: 'Nationwide Children\'s Hospital',
    city: 'Columbus',
    country: 'USA',
    region: 'North America',
    specialty: 'DMD & Gene Therapy',
    subIndications: ['dmd'],
    influenceScore: 97,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-251'],
    recentInteractions: 5,
    publications: 380,
    focusAreas: ['DMD gene therapy', 'Microdystrophin', 'Exon-skipping trials'],
    conferenceAppearances: 15,
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    platformView: 'Elevidys-aligned; publicly cautious on systemic oligo delivery. The "show me 104-week data" archetype (AI1).',
    crossIndication: false,
    recommendedStrategy:
      'Engage carefully around long-term FORCE biodistribution data (A1). Do not push platform narrative prematurely; lead with science.',
    email: 'jerry.mendell@nationwidechildrens.org',
    provenance: 'public',
  },
  {
    id: 'kol-7',
    name: 'Francesco Muntoni',
    institution: 'UCL Great Ormond Street Institute of Child Health',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    specialty: 'DMD & Congenital Muscular Dystrophies',
    subIndications: ['dmd'],
    influenceScore: 95,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-251'],
    recentInteractions: 4,
    publications: 410,
    focusAreas: ['DMD clinical trials', 'Exon-skipping PMOs', 'Ultra-rare NM disorders'],
    conferenceAppearances: 13,
    sentiment: 'Neutral',
    sentimentTrend: 'shifting toward',
    platformView: 'Historically PMO-aligned; warming to FORCE mechanism after WMS 2025 delivery session',
    crossIndication: false,
    recommendedStrategy:
      'Flagship EU DMD engagement for DELIVER readouts. Opportunity to co-develop FORCE-vs-PMO scientific narrative.',
    email: 'f.muntoni@ucl.ac.uk',
    provenance: 'public',
  },
  {
    id: 'kol-8',
    name: 'Craig McDonald',
    institution: 'UC Davis Health',
    city: 'Sacramento',
    country: 'USA',
    region: 'North America',
    specialty: 'DMD Natural History & Functional Assessment',
    subIndications: ['dmd'],
    influenceScore: 91,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-251'],
    recentInteractions: 5,
    publications: 240,
    focusAreas: ['DMD natural history', 'Ambulatory and non-ambulatory endpoints', 'NSAA / 6MWT'],
    conferenceAppearances: 10,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'Interested in FORCE for durability arguments; frames conversation around functional preservation',
    crossIndication: false,
    recommendedStrategy:
      'Engage for DELIVER endpoint interpretation. Candidate co-author on DMD sequencing algorithm (A3).',
    email: 'cmmcdonald@ucdavis.edu',
    provenance: 'public',
  },
  {
    id: 'kol-9',
    name: 'Eugenio Mercuri',
    institution: 'Catholic University of Rome',
    city: 'Rome',
    country: 'Italy',
    region: 'Europe',
    specialty: 'DMD & Pediatric Neuromuscular',
    subIndications: ['dmd'],
    influenceScore: 89,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-251'],
    recentInteractions: 3,
    publications: 320,
    focusAreas: ['DMD clinical trials', 'Pediatric natural history', 'Ambulatory outcomes'],
    conferenceAppearances: 11,
    sentiment: 'Advocate',
    sentimentTrend: 'stable',
    platformView: 'Mechanism-agnostic; strong functional-endpoint voice',
    crossIndication: false,
    recommendedStrategy:
      'Key EU DMD engagement for DELIVER functional-endpoint interpretation.',
    email: 'eugenio.mercuri@unicatt.it',
    provenance: 'public',
  },

  // ─── DM1 specialists ───
  {
    id: 'kol-10',
    name: 'Charles Thornton',
    institution: 'University of Rochester Medical Center',
    city: 'Rochester',
    country: 'USA',
    region: 'North America',
    specialty: 'Myotonic Dystrophy',
    subIndications: ['dm1'],
    influenceScore: 96,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-101'],
    recentInteractions: 9,
    publications: 180,
    focusAreas: ['DM1 molecular pathogenesis', 'Antisense oligonucleotide therapeutics', 'Clinical endpoints'],
    conferenceAppearances: 14,
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    platformView: 'Mechanistically sold on ASO approaches; waiting on durability data before publicly endorsing FORCE vs AOC',
    crossIndication: false,
    recommendedStrategy:
      'Deepen engagement around ACHIEVE endpoint interpretation and post-approval RWE design. Priority speaker for MDF 2026.',
    email: 'charles_thornton@urmc.rochester.edu',
    provenance: 'public',
  },
  {
    id: 'kol-11',
    name: 'John Day',
    institution: 'Stanford University School of Medicine',
    city: 'Palo Alto',
    country: 'USA',
    region: 'North America',
    specialty: 'Neuromuscular (DM1 & SMA)',
    subIndications: ['dm1'],
    influenceScore: 92,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-101'],
    recentInteractions: 6,
    publications: 165,
    focusAreas: ['DM1 natural history', 'Clinical trial design in neuromuscular', 'Functional endpoints'],
    conferenceAppearances: 11,
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    platformView: 'Public advocate for RNA-targeted approaches; ACHIEVE sub-investigator',
    crossIndication: false,
    recommendedStrategy:
      'Leverage for DM1-ActiveC patient-reported outcome storytelling. Engage on candidate-selection primer development (AI2).',
    email: 'jwday@stanford.edu',
    provenance: 'public',
  },
  {
    id: 'kol-12',
    name: 'Nathalie Angeard',
    institution: 'Institut de Myologie, Paris',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    specialty: 'DM1 Cognitive & Behavioral Phenotype',
    subIndications: ['dm1'],
    influenceScore: 81,
    engagementTier: 'Tier 2',
    productAlignment: ['dyne-101'],
    recentInteractions: 2,
    publications: 95,
    focusAreas: ['DM1 CNS manifestations', 'Cognitive assessment'],
    conferenceAppearances: 6,
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    platformView: 'Watching FORCE CNS penetration data closely',
    crossIndication: false,
    recommendedStrategy:
      'Engage around FORCE CNS penetration data — strategic for DM1 cognitive-phenotype narrative.',
    email: 'nathalie.angeard@inserm.fr',
    provenance: 'public',
  },
  {
    id: 'kol-13',
    name: 'Hiroshi Matsumura',
    institution: 'Osaka University Graduate School of Medicine',
    city: 'Osaka',
    country: 'Japan',
    region: 'Asia',
    specialty: 'DM1 & Myotonic Disorders',
    subIndications: ['dm1'],
    influenceScore: 82,
    engagementTier: 'Tier 2',
    productAlignment: ['dyne-101'],
    recentInteractions: 2,
    publications: 140,
    focusAreas: ['DM1 cardiac manifestations', 'Japanese DM1 natural history cohort'],
    conferenceAppearances: 5,
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    platformView: 'Mechanism-interested; cardiac story resonant',
    crossIndication: false,
    recommendedStrategy:
      'APAC engagement anchor. Opportunity to surface FORCE cardiac-tissue distribution data.',
    email: 'hiroshi.matsumura@osaka-u.ac.jp',
    provenance: 'synthesized',
  },

  // ─── Pompe specialists ───
  {
    id: 'kol-14',
    name: 'Priya Kishnani',
    institution: 'Duke University Medical Center',
    city: 'Durham',
    country: 'USA',
    region: 'North America',
    specialty: 'Pompe Disease & Lysosomal Disorders',
    subIndications: ['pompe'],
    influenceScore: 93,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-pompe'],
    recentInteractions: 4,
    publications: 260,
    focusAreas: ['Pompe disease', 'Enzyme replacement therapy', 'Newborn screening'],
    conferenceAppearances: 9,
    sentiment: 'Advocate',
    sentimentTrend: 'shifting toward',
    platformView: 'Engaged on FORCE-Pompe preclinical data; sees durability as the unlock for ERT transition',
    crossIndication: false,
    recommendedStrategy:
      'Anchor Pompe pre-IND engagement. Leverage for patient-advocacy bridging (LP5).',
    email: 'priya.kishnani@duke.edu',
    provenance: 'public',
  },

  // ─── FSHD specialists ───
  {
    id: 'kol-15',
    name: 'Silvère van der Maarel',
    institution: 'Leiden University Medical Center',
    city: 'Leiden',
    country: 'Netherlands',
    region: 'Europe',
    specialty: 'FSHD Molecular Biology',
    subIndications: ['fshd'],
    influenceScore: 91,
    engagementTier: 'Tier 1',
    productAlignment: ['dyne-fshd'],
    recentInteractions: 2,
    publications: 210,
    focusAreas: ['FSHD molecular genetics', 'DUX4 biology', 'Epigenetic regulation'],
    conferenceAppearances: 9,
    sentiment: 'Neutral',
    sentimentTrend: 'shifting toward',
    platformView: 'Mechanism-focused; wants DUX4 protein-suppression quantification (AI6 anchor)',
    crossIndication: false,
    recommendedStrategy:
      'Candidate scientific partner on FSHD DUX4 protein-suppression evidence review (A7).',
    email: 's.m.van_der_maarel@lumc.nl',
    provenance: 'public',
  },

  // ─── Emerging voices (Tier 3) — watchlist / sentiment trending ───
  {
    id: 'kol-16',
    name: 'Barbara Smith-Anderson',
    institution: 'Seattle Children\'s Hospital',
    city: 'Seattle',
    country: 'USA',
    region: 'North America',
    specialty: 'Pediatric Neuromuscular',
    subIndications: ['dmd', 'pompe'],
    influenceScore: 76,
    engagementTier: 'Tier 3',
    productAlignment: ['dyne-251', 'dyne-pompe'],
    recentInteractions: 1,
    publications: 62,
    focusAreas: ['Pediatric DMD care', 'Infantile Pompe'],
    conferenceAppearances: 3,
    sentiment: 'Emerging',
    sentimentTrend: 'shifting toward',
    platformView: 'Newly vocal at regional meetings; rising influence in Pacific Northwest care network',
    crossIndication: true,
    recommendedStrategy:
      'Emerging voice — candidate for Tier 2 promotion within 12 months. Early engagement opportunity.',
    email: 'barbara.smith@seattlechildrens.org',
    provenance: 'synthesized',
  },
  {
    id: 'kol-17',
    name: 'Marcus Reid',
    institution: 'Royal London Hospital',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    specialty: 'Adult Neuromuscular',
    subIndications: ['dm1', 'fshd'],
    influenceScore: 74,
    engagementTier: 'Tier 3',
    productAlignment: ['dyne-101', 'dyne-fshd'],
    recentInteractions: 1,
    publications: 48,
    focusAreas: ['Adult-onset DM1', 'FSHD genetic counseling'],
    conferenceAppearances: 3,
    sentiment: 'Emerging',
    sentimentTrend: 'shifting toward',
    platformView: 'Recent WMS 2025 poster touching both DM1 and FSHD — emerging cross-indication voice',
    crossIndication: true,
    recommendedStrategy:
      'Watch-list priority — exactly the portfolio-ready voice AI4 flagged as scarce.',
    email: 'marcus.reid@nhs.net',
    provenance: 'synthesized',
  },
  {
    id: 'kol-18',
    name: 'Nicolas Levy',
    institution: 'Aix-Marseille University',
    city: 'Marseille',
    country: 'France',
    region: 'Europe',
    specialty: 'Neuromuscular Genetics & Therapeutics',
    subIndications: ['dmd', 'dm1'],
    influenceScore: 83,
    engagementTier: 'Tier 2',
    productAlignment: ['dyne-251', 'dyne-101'],
    recentInteractions: 2,
    publications: 210,
    focusAreas: ['Genetic muscular dystrophies', 'Therapy development', 'Rare disease policy'],
    conferenceAppearances: 6,
    sentiment: 'Neutral',
    sentimentTrend: 'stable',
    platformView: 'FORCE-curious; sensitive to regulatory-framework questions in EU',
    crossIndication: true,
    recommendedStrategy:
      'EU policy-aware engagement. Useful voice on ICNMD-facing platform narrative.',
    email: 'nicolas.levy@univ-amu.fr',
    provenance: 'public',
  },
];
